// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The POSIX account information associated with a Google account.
public struct PosixAccount: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Only one POSIX account can be marked as primary.
  public var primary: Swift.Bool = Swift.Bool()

  /// The username of the POSIX account.
  public var username: Swift.String = Swift.String()

  /// The user ID.
  public var uid: Swift.Int64 = Swift.Int64()

  /// The default group ID.
  public var gid: Swift.Int64 = Swift.Int64()

  /// The path to the home directory for this account.
  public var homeDirectory: Swift.String = Swift.String()

  /// The path to the logic shell for this account.
  public var shell: Swift.String = Swift.String()

  /// The GECOS (user information) entry for this account.
  public var gecos: Swift.String = Swift.String()

  /// System identifier for which account the username or uid applies to.
  /// By default, the empty value is used.
  public var systemId: Swift.String = Swift.String()

  /// Output only. A POSIX account identifier.
  public var accountId: Swift.String = Swift.String()

  /// The operating system type where this account applies.
  public var operatingSystemType: OperatingSystemType = OperatingSystemType()

  /// Output only. The canonical resource name.
  public var name: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PosixAccount`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PosixAccount().with { $0.primary = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let primary = CodingKeys(stringValue: "primary")
    static let username = CodingKeys(stringValue: "username")
    static let uid = CodingKeys(stringValue: "uid")
    static let gid = CodingKeys(stringValue: "gid")
    static let homeDirectory = CodingKeys(stringValue: "homeDirectory")
    static let shell = CodingKeys(stringValue: "shell")
    static let gecos = CodingKeys(stringValue: "gecos")
    static let systemId = CodingKeys(stringValue: "systemId")
    static let accountId = CodingKeys(stringValue: "accountId")
    static let operatingSystemType = CodingKeys(stringValue: "operatingSystemType")
    static let name = CodingKeys(stringValue: "name")

    static let _knownKeys: Set<Swift.String> = [
      "primary",
      "username",
      "uid",
      "gid",
      "homeDirectory",
      "shell",
      "gecos",
      "systemId",
      "accountId",
      "operatingSystemType",
      "name",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .primary) {
      self.primary = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .username) {
      self.username = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .gid) {
      self.gid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .homeDirectory) {
      self.homeDirectory = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .shell) {
      self.shell = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gecos) {
      self.gecos = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .systemId) {
      self.systemId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .accountId) {
      self.accountId = value
    }
    if let value = try container.decodeIfPresent(
      OperatingSystemType.self, forKey: .operatingSystemType)
    {
      self.operatingSystemType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.primary, forKey: .primary)
    try container.encode(self.username, forKey: .username)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.gid, forKey: .gid)
    try container.encode(self.homeDirectory, forKey: .homeDirectory)
    try container.encode(self.shell, forKey: .shell)
    try container.encode(self.gecos, forKey: .gecos)
    try container.encode(self.systemId, forKey: .systemId)
    try container.encode(self.accountId, forKey: .accountId)
    try container.encode(self.operatingSystemType, forKey: .operatingSystemType)
    try container.encode(self.name, forKey: .name)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oslogin.common.PosixAccount"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
