// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The POSIX account information associated with a Google account.
public struct PosixAccount: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Only one POSIX account can be marked as primary.
  public var primary: Swift.Bool = Swift.Bool()

  /// The username of the POSIX account.
  public var username: Swift.String = Swift.String()

  /// The user ID.
  public var uid: Swift.Int64 = Swift.Int64()

  /// The default group ID.
  public var gid: Swift.Int64 = Swift.Int64()

  /// The path to the home directory for this account.
  public var homeDirectory: Swift.String = Swift.String()

  /// The path to the logic shell for this account.
  public var shell: Swift.String = Swift.String()

  /// The GECOS (user information) entry for this account.
  public var gecos: Swift.String = Swift.String()

  /// System identifier for which account the username or uid applies to.
  /// By default, the empty value is used.
  public var systemId: Swift.String = Swift.String()

  /// Output only. A POSIX account identifier.
  public var accountId: Swift.String = Swift.String()

  /// The operating system type where this account applies.
  public var operatingSystemType: OperatingSystemType = OperatingSystemType()

  /// Output only. The canonical resource name.
  public var name: Swift.String = Swift.String()

  /// Initialize a new instance of `PosixAccount`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PosixAccount().with { $0.primary = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oslogin.common.PosixAccount"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
